; PlatformIO Project Configuration File
; https://docs.platformio.org/page/projectconf.html

[env:adafruit_feather_nrf52840]
platform = nordicnrf52
board = adafruit_feather_nrf52840
framework = arduino
monitor_speed = 115200

lib_deps =
    paulstoffregen/OneWire
    milesburton/DallasTemperature
    sparkfun/SparkFun MAX1704x Fuel Gauge Arduino Library
    sparkfun/SparkFun u-blox GNSS Arduino Library
    adafruit/Adafruit MPU6050
    adafruit/Adafruit SHT31 Library
    adafruit/Adafruit Unified Sensor
    adafruit/Adafruit BusIO
    lib/ml-model

build_flags =
    -DEI_CLASSIFIER_ENABLE_DETECTION=0
    -DEI_CLASSIFIER_ENABLE_CLASSIFICATION=0
    -DEI_CLASSIFIER_ENABLE_REGRESSION=1

lib_ldf_mode = deep+
