; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:adafruit_feather_nrf52840]
platform = nordicnrf52
board = adafruit_feather_nrf52840
framework = arduino

lib_deps =
    https://github.com/DFRobot/DFRobot_SHT3x.git
    adafruit/Adafruit_RV1805
    adafruit/Adafruit_MPU6050
    adafruit/Adafruit_SPIFlash
    adafruit/Adafruit_GPS
    paulstoffregen/OneWire
    DallasTemperature/DallasTemperature
    sparkfun/SparkFun LiPo Fuel Gauge
    tensorflow/Arduino_TensorFlowLite

monitor_speed = 115200
monitor_dtr = off
monitor_rts = off